<?php

/**
 * @file
 * Contains pss_pse.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pss_pse_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pss_pse module.
    case 'help.page.pss_pse':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Harmonie Mutuelle PSS PSE') . '</p>';
      return $output;

    default:
  }
}

function pss_pse_preprocess_page(&$page) {
  $apiService = Drupal::service('pss_pse.api_tarifer');

  $body = [
    "codeOffre" => "HGAV",
    "dateEffet" => "2020-08-05T13:08:40.577Z",
    "donneeTarifantes" => [
      [
        "cle" => "PROSPECT_DATE_NAISSANCE",
        "dataType" => "DATE",
        "valeur" => "01/07/1981",
      ],
      [
        "cle" => "PROTECTION_CONJOINT",
        "dataType" => "BOOLEAN",
        "valeur" => "true",
      ],
      [
        "cle" => "PROTECTION_ENFANTS",
        "dataType" => "BOOLEAN",
        "valeur" => "true",
      ],
      [
        "cle" => "NOMBRE_ENFANTS",
        "dataType" => "BOOLEAN",
        "valeur" => "2",
      ],
    ],
  ];

 /* $res = Drupal::httpClient()->post('https://rec.api.harmonie-mutuelle.fr/services/tarifer-indiv/v1',
    [
      'auth' => ['USER_PFS', 'ScK5mYa2u8aT6Fgaz'],
      'headers' => [
      //  'Authorization' => 'Basic ' . base64_encode('USER_PFS:ScK5mYa2u8aT6Fgaz'),
        'Apikey' => '5F75DDCEDC4593B792556B9844D03703672C5CE1047053C2B407A619D0641702',
        'Content-Type' => 'application/json',
      ],
      'json' => $body,
    ]);

  ksm($res->getBody()->getContents());*/

  ksm($apiService->send($body, 'indiv'));

}
