<?php

/**
 * @file
 * Contains pss_pse.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pss_pse_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pss_pse module.
    case 'help.page.pss_pse':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Harmonie Mutuelle PSS PSE') . '</p>';
      return $output;

    default:
  }
}

function pss_pse_theme() {
  return [
    'poc_form' => [
      'variables' => [
        'form' => NULL,
      ],
    ],
  ];
}

function pss_pse_preprocess_page(&$page) {

  $body = [
    "codeOffre" => "HGAV",
    "dateEffet" => "2020-08-05T13:08:40.577Z",
    "donneeTarifantes" => [
      [
        "cle" => "PROSPECT_DATE_NAISSANCE",
        "dataType" => "DATE",
        "valeur" => "01/07/1981",
      ],
      [
        "cle" => "PROTECTION_CONJOINT",
        "dataType" => "BOOLEAN",
        "valeur" => "true",
      ],
      [
        "cle" => "PROTECTION_ENFANTS",
        "dataType" => "BOOLEAN",
        "valeur" => "true",
      ],
      [
        "cle" => "NOMBRE_ENFANTS",
        "dataType" => "BOOLEAN",
        "valeur" => "2",
      ],
    ],
  ];
  /*$apiService = Drupal::service('pss_pse.api_tarifer');
  ksm($apiService->send($body, 'indiv'));*/

}
