<?php

/**
 * Implements hook_library_info_alter().
 */
function tac_google_map_field_library_info_alter(&$libraries, $extension) {
  if ($extension == 'google_map_field') {
    unset($libraries['google-map-field-renderer']);
    unset($libraries['google-map-apis']);
  }
}

/**
 ** Implements hook_theme().
 **/
function tac_google_map_field_theme($existing, $type, $theme, $path) {

  $templates = $path . '/templates';

  $return['google_map_field'] = [
    'template' => 'google_map_field',
    'path' => $templates
  ];
  return $return;
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function tac_google_map_field_menu_links_discovered_alter(&$links) {
  unset($links['gmap.field.admin']);
}