<?php

/**
 * @file
 * Contains budge.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function budge_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the budge module.
    case 'help.page.budge':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function budge_theme($existing, $type, $theme, $path) {
  return [
    'budge_main' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
    'budge_export' => [
      'variables' => []
    ],
  ];
}

/**
 * Implements hook_entity_presave().
 */
function budge_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
 if ($entity->bundle() == 'budget') {
   Drupal::service('cache.render')->invalidate('route');
 }
}
