<?php

/**
 * @file
 * Contains icon_selector.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function icon_selector_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the icon_selector module.
    case 'help.page.icon_selector':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Sélection d&#039;icone') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function icon_selector_theme() {
  return [
    'icon_selector' => [
      'render element' => 'children',
    ],
  ];
}
