<?php

/**
 * @file
 * Contains list_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function list_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the list_page module.
    case 'help.page.list_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Content list page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess().
 */
function list_page_preprocess_node(&$variables) {
  $node = $variables['elements']['#node'];
  $viewMode = $variables['elements']['#view_mode'];
  if ($node->bundle() == 'article_list' && $viewMode == 'full') {

    // Get Form.
    $form = Drupal::formBuilder()->getForm('Drupal\list_page\Form\ArticleListForm');

    // Initiate list manager.
    $lisPageManager = Drupal::service('list_page.manager')->create();

    // Start search. Use buildConditions() for adding extra conditions.
    //getResults(String entityType, array queryConditions, int pager = null)
    $results = $lisPageManager->getResults('node',
      [
        ['status', 1],
        ['type', 'article'],
      ],
      4);

    // Render
    $variables['content']['form'] = $form;
    $variables['content']['result']['#markup'] = implode(',', $results);
    $variables['content']['pager'] = ['#type' => 'pager'];
  }
}

/**
 * Implements hook_theme().
 */
function list_page_theme() {
  return [
    'article_list_page' => [
      'variables' => [
        'result' => NULL,
      ],
    ],
  ];
}
