<?php

/**
 * @file
 * Contains d8_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pss_pse module.
    case 'help.page.d8_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 8 api') . '</p>';
      return $output;

    default:
  }
}

function d8_api_theme() {
  return [
    'd8_api_form' => [
      'variables' => [
        'form' => NULL,
      ],
    ],
  ];
}

