<?php

namespace Drupal\d8_api\Service;

/**
 * Class Mapping
 *
 * @package Drupal\d8_api\Service
 */
class Mapping {

  const DATA_TYPE = [
    "PROSPECT_DATE_NAISSANCE" => "DATE",
    "PROTECTION_CONJOINT" => "BOOLEAN",
    "CONJOINT_DATE_NAISSANCE" => "DATE",
    "PROTECTION_ENFANTS" => "BOOLEAN",
    "NOMBRE_ENFANTS" => "NUMBER",
    "ENFANT_DATE_NAISSANCE" => "DATE",
    "ENFANT_DATE_NAISSANCE_1" => "DATE",
    "ENFANT_DATE_NAISSANCE_2" => "DATE",
    "ENFANT_DATE_NAISSANCE_3" => "DATE",
    "ENFANT_DATE_NAISSANCE_4" => "DATE",
    "ENFANT_DATE_NAISSANCE_5" => "DATE",
    "REGIME_OBLIGATOIRE" => "STRING",
    "CODE_POSTAL" => "STRING",
    "CODE_NIVEAU_PSE" => "STRING",
    "CODE_PH" => "NUMBER",
    "STRUCTURE_COTISATION" => "STRING",
    "REDUCTION_TNS" => "BOOLEAN",
    "BUDGET_MALIN" => "BOOLEAN",
    "CODE_NIVEAU_GARANTIE" => "STRING",
    "MEDICAMENTS_SANS_ORDONNANCE" => "BOOLEAN",
    "SOINS_MEDICAUX" => "BOOLEAN",
    "OPTIQUE_DENTAIRE" => "BOOLEAN",
    "CHAMBRE_PARTICULIERE" => "BOOLEAN",
    "MONTANT_CAPITAL" => "NUMBER",
  ];

}
