<?php

/**
 * @file
 * Contains article_list.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function article_list_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the article_list module.
    case 'help.page.article_list':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess().
 */
function article_list_preprocess_node(&$variables) {
  /**
   * @var \Drupal\node\Entity\Node
   */
  $node = $variables['elements']['#node'];
  $viewMode = $variables['elements']['#view_mode'];

  if ($node->bundle() == 'article_list' && $viewMode == 'full') {

    /**
     * @var \Drupal\article_list\Manager\ArticleListManager $articleListManager
     */
    $articleListManager = Drupal::service('article_list.manager');

    $result = $articleListManager->getResults();
    $form = Drupal::formBuilder()->getForm('Drupal\article_list\Form\ArticleListForm');

    /* Sending variables to template. */
    $variables['content']['form'] = $form;
    $variables['content']['result'] = $result;

    /* Managing caches. */
    // Adding cache context for url query args.
    $variables['content']['result']['#cache']['contexts'][] = 'url.query_args';
    // Adding custom cache tags to be invalidate when an node Article will be created or updated.
    $variables['elements']['#cache']['tags'][] = 'article_list_page';

  }
}
