<?php

/**
 * @file
 * Contains article_list.module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function article_list_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the article_list module.
    case 'help.page.article_list':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess().
 */
function article_list_preprocess_node(&$variables) {
  /**
   * @var \Drupal\node\Entity\Node
   */
  $node = $variables['elements']['#node'];
  $viewMode = $variables['elements']['#view_mode'];

  if ($node->bundle() == 'article_list' && $viewMode == 'full') {

    /**
     * @var \Drupal\article_list\Manager\ArticleListManager $articleListManager
     */
    $articleListManager = Drupal::service('article_list.manager');

    /* Getting results. */
    $results = $articleListManager->getResults();
    /* Building exposed filters form. */
    $form = Drupal::formBuilder()->getForm('Drupal\article_list\Form\ArticleListForm');

    /* Sending render arrays to template. */
    $variables['content']['form'] = $form;
    $variables['content']['results'] = $results;

    /* Adding pager. */
    $variables['content']['pager'] = ['#type' => 'pager'];

  }
}

/**
 * Implements hook_entity_presave().
 */
function article_list_entity_presave(EntityInterface $entity) {
  $type = $entity->getEntityTypeId();
  $bundle = $entity->bundle();

  if ($type == 'node' && $bundle == 'article') {
    // Invalidating results cache in article list page.
    Cache::invalidateTags(['article_list_results']);
  }

}
